apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: thyc7v0u6-nodejs 
  janus-idp.io/tekton: thyc7v0u6-nodejs
  backstage.io/kubernetes-id: thyc7v0u6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: thyc7v0u6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml