apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: thyc7v0u6-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: thyc7v0u6-nodejs 
  name: thyc7v0u6-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: thyc7v0u6-nodejs 
